In [1]:
import numpy as np
import pandas as pd

In [4]:
# 가장 쉬운 dataframe 만들기: 10*10zmrl , random값으로 생성
df = pd.DataFrame(
    np.random.rand(10, 10)
)
df

,0,1,2,3,4,5,6,7,8,9
0,0.410745,0.124383,0.132830,0.445314,0.213153,0.443892,0.471283,0.937590,0.672477,0.417221
1,0.887492,0.723856,0.688976,0.023638,0.275160,0.769983,0.002227,0.807474,0.810123,0.855653
2,0.489746,0.318083,0.155662,0.285575,0.040083,0.946773,0.781873,0.686874,0.453842,0.562646
3,0.075154,0.906560,0.663953,0.351298,0.964326,0.812533,0.295257,0.570843,0.327674,0.746330
4,0.972046,0.716139,0.419000,0.720993,0.910953,0.535881,0.754196,0.130708,0.478891,0.569373
5,0.480802,0.558223,0.367937,0.832984,0.289015,0.246094,0.233648,0.434717,0.622461,0.927433
6,0.029274,0.291642,0.549414,0.070642,0.234667,0.647462,0.404544,0.380871,0.978231,0.368406
7,0.996891,0.380099,0.306799,0.251138,0.888937,0.875141,0.995700,0.759273,0.322301,0.231180
8,0.447604,0.967851,0.889450,0.806888,0.098741,0.563620,0.426497,0.762110,0.015055,0.884271
9,0.569174,0.612904,0.258185,0.665134,0.760546,0.189455,0.039077,0.804736,0.704135,0.276034

In [7]:
index = pd.date_range('2020-01-01', periods=10, freq='D')

df = pd.DataFrame(
    np.random.rand(10, 3), index, columns= ['A', 'B', 'C']
)
df

                   A         B         C
2020-01-01  0.628506  0.231426  0.327320
2020-01-02  0.370512  0.718637  0.105215
2020-01-03  0.570235  0.646814  0.810376
2020-01-04  0.697015  0.915477  0.747678
2020-01-05  0.857297  0.845488  0.886854
2020-01-06  0.244695  0.554909  0.436629
2020-01-07  0.166320  0.431836  0.235171
2020-01-08  0.717241  0.834736  0.909465
2020-01-09  0.748370  0.103070  0.934931
2020-01-10  0.419144  0.284839  0.492568